include(
    ":app",
    ":di",
    ":navigation",
    ":data-local",
    ":bases:base-domain",
    ":bases:base-data-remote",
    ":bases:core",
    ":features:feature-auth:ui",
    ":features:feature-auth:domain",
    ":features:feature-auth:data",
    ":features:feature-auth:data-remote",
    ":features:feature-home:ui",
    ":features:feature-home:data",
    ":features:feature-home:domain",
    ":features:feature-home:data-remote"
)
